const pages={
  dashboard:{title:'KPI Dashboard',sub:'Overview of Maintenance Performance',action:'Filter',metrics:[['Planned Maintenance Compliance','92%','✓','green'],['PM Compliance (On-Time)','88%','◷','blue'],['Total Downtime (Hours)','23.6','◉','red'],['MTBF (Hours)','156.7','▥','blue'],['MTTR (Hours)','2.45','⚒','orange'],['Work Orders Completed','128','▣','purple']],type:'kpi'},
  'work-orders':{title:'Work Orders',sub:'Manage and track all maintenance work orders',action:'+ New Work Order',metrics:[['Total Work Orders','146','▤','blue'],['Completed','128','✓','green'],['In Progress','18','◷','orange'],['On Hold','6','Ⅱ','blue'],['Overdue','12','◉','red'],['Avg. Completion Time','5.6 hrs','◷','green']],columns:['WO No.','Type','Equipment','Problem / Description','Priority','Status','Assigned To','Due Date','Created On'],type:'work'},
  'daily-reports':{title:'Daily Reports',sub:'Track technician daily activities and maintenance work',action:'+ New Daily Report',metrics:[['Total Reports','86','▤','blue'],['Reports Completed','68','✓','green'],['In Progress','12','◷','orange'],['Pending Approval','6','⌛','purple'],['Rejected','2','×','red'],['Avg. Downtime (hrs)','2.45','◷','green']],columns:['Report No.','Date','Shift','Technician','Plant / Line','Work Orders','Status','Downtime (hrs)','Submitted On'],type:'report'},
  'pm-schedule':{title:'PM Schedule',sub:'Plan, schedule and track preventive maintenance tasks',action:'+ New PM Task',metrics:[['Total PM Tasks','124','▣','blue'],['Due This Period','38','▧','orange'],['Overdue','5','◷','red'],['Completed','71','✓','green'],['Compliance (%)','92%','◈','purple'],['Avg. Completion Time','2.1 hrs','◷','green']],columns:['PM Task ID','Task Name','Equipment','PM Type','Frequency','Next Due Date','Status','Priority','Assigned To'],type:'pm'},
  equipment:{title:'Equipment',sub:'Manage and track all equipment and asset information',action:'+ Add Equipment',metrics:[['Total Equipment','186','▣','blue'],['Operational','156','✓','green'],['Under Maintenance','18','⚒','orange'],['Out of Service','12','×','red'],['Avg. Age (Years)','6.7','▣','purple'],['Critical Assets','24','◈','red']],columns:['Equipment Code','Equipment Name','Category','Location (Plant / Line)','Status','Condition','Criticality'],type:'equipment'},
  sop:{title:'SOP (Standard Operating Procedures)',sub:'Access and manage standard operating procedures for equipment',action:'+ Add SOP',metrics:[['Total SOPs','142','▤','blue'],['Published','118','✓','green'],['Under Review','12','◷','orange'],['Draft','7','✎','purple'],['Outdated','5','!','red'],['Compliance','94%','◈','green']],columns:['SOP Code','SOP Title','Category','Version','Status','Last Review'],type:'sop'},
  'machine-records':{title:'Machine Records',sub:'View and track complete history and maintenance records for each machine',action:'⇧ Export',metrics:[['Total Records','256','▤','blue'],['Maintenance Records','128','⚒','green'],['Inspection Records','74','▧','orange'],['Repairs / Overhauls','32','⚒','purple'],['Parts Replacements','22','□','red'],['Total Downtime (hrs)','18.6','◷','green']],columns:['Record No.','Date & Time','Record Type','Description','Performed By','Downtime (hrs)'],type:'records'},
  kpi:null,reports:null,'spare-parts':null,technicians:null,settings:null,notifications:null
};pages.kpi=pages.dashboard;pages.reports={...pages.dashboard,title:'Reports',sub:'Review maintenance reports and summaries',action:'⇧ Export'};pages['spare-parts']={...pages.equipment,title:'Spare Parts',sub:'Manage parts used in maintenance activities',action:'+ Add Part'};pages.technicians={...pages.equipment,title:'Technicians',sub:'Manage maintenance team and workload',action:'+ Add Technician'};pages.settings={...pages.equipment,title:'Settings',sub:'Configure CMMS preferences and permissions',action:'Save Settings'};pages.notifications={...pages.equipment,title:'Notifications',sub:'Review recent system updates and approvals',action:'Mark All Read'};
const equipment=[['HM-001','Hammer Mill 01','Milling','Plant 1 / Line 3'],['PP-001','Pellet Press 01','Pressing','Plant 1 / Line 2'],['MX-001','Mixer 01','Mixing','Plant 1 / Line 1'],['CL-001','Cooler 01','Cooling','Plant 1 / Line 2'],['CV-003','Conveyor 03','Conveying','Plant 1 / Line 3'],['BO-001','Boiler 01','Utilities','Plant 1 / Boiler Room'],['GP-001','Grease Pump 01','Lubrication','Plant 1 / Line 1']];
const records=[['WO-2505-0146','Corrective','Hammer Mill 01 (HM-001)','Bearing failure on main shaft','High','In Progress','Ali H.','05/06/2025','31/05/2025'],['WO-2505-0145','Preventive','Pellet Press 01 (PP-001)','Monthly preventive maintenance','Medium','Completed','Hassan M.','31/05/2025','30/05/2025'],['WO-2505-0144','Routine','Mixer 01 (MX-001)','Routine inspection','Low','Completed','Ahmed R.','30/05/2025','30/05/2025'],['WO-2505-0143','Corrective','Cooler 01 (CL-001)','Vibration issue','High','On Hold','Omar K.','02/06/2025','29/05/2025'],['WO-2505-0142','Preventive','Conveyor 03 (CV-003)','Belt tension check','Medium','In Progress','Sajjad A.','01/06/2025','28/05/2025']];
const badge=(text)=>{let c=/Completed|Operational|Published|Good/.test(text)?'green':/Overdue|Out of|High|Rejected/.test(text)?'red':/Progress|Maintenance|Due|Medium/.test(text)?'orange':/Draft|Approval|Hold/.test(text)?'purple':'blue';return `<span class="badge ${c}">${text}</span>`};
function metrics(items){return items.map((m,i)=>`<article class="metric" style="--accent:${['#1269f3','#009b64','#fb6910','#7137e9','#f22d3b','#008d9c'][i]};--tint:${['#eaf1ff','#e8f8f2','#fff3e6','#f2ebff','#fff0f0','#e5f8f2'][i]}"><h3>${m[0]}</h3><b>${m[1]}</b><span class="glyph">${m[2]}</span><div class="trend">↑ ${8+i}% vs Last Period</div></article>`).join('')}
function tableRows(type){if(type==='equipment')return equipment.map(r=>`<tr><td class="code">${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${badge(r[0]==='MX-001'?'Under Maintenance':'Operational')}</td><td>${badge(r[0]==='MX-001'?'Fair':'Good')}</td><td>${badge(r[0]==='HM-001'?'High':'Medium')}</td><td class="actions">⊙ ⋮</td></tr>`).join('');if(type==='sop')return ['Daily Inspection','Start-up Procedure','Normal Operation','Shutdown Procedure','Bearing Replacement','Lubrication Procedure'].map((x,i)=>`<tr><td class="code">SOP-HM-001-00${i+1}</td><td>${x}</td><td>${i<4?'Operation':'Maintenance'}</td><td>2.${i}</td><td>${badge(i===4?'Under Review':'Published')}</td><td>${15-i}/05/2025</td><td class="actions">⊙ ⋮</td></tr>`).join('');if(type==='records')return ['Replaced main bearing and lubricated gearbox','Routine inspection of belts and pulleys','Replaced V-belts (2 pcs)','Fixed vibration issue in rotor shaft','Cleaned air filter and checked alignment'].map((x,i)=>`<tr><td class="code">MR-2505-025${6-i}</td><td>31/05/2025<br>10:15 AM</td><td>${badge(i%2?'Inspection':'Maintenance')}</td><td>${x}</td><td>${['Ali Hassan','Hassan M.','Ahmed R.','Omar K.','Sajjad A.'][i]}</td><td>${[2.3,0,1.2,3.1,.8][i].toFixed(2)}</td><td class="actions">⊙ ⋮</td></tr>`).join('');let rows=records;if(type==='report')rows=records.map((r,i)=>[`DR-2505-008${6-i}`,r[8],['A','B','C'][i%3],r[6],r[3].includes('Hammer')?'Plant 1 / Line 3':'Plant 1 / Line 2',i%3+1,i===2?'Pending Approval':'Completed',(i+.9).toFixed(2),r[8]+' 04:15 PM']);if(type==='pm')rows=records.map((r,i)=>[`PM-2505-01${24-i}`,r[3],r[2],'Preventive',i<3?'Weekly':'Monthly',r[7],i===0?'Due Today':'Upcoming',r[4],r[6]]);return rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${i===0?'code':''}">${['Corrective','Preventive','Routine','Completed','In Progress','On Hold','Pending Approval','Due Today','Upcoming','High','Medium','Low'].includes(v)?badge(v):v}</td>`).join('')}<td class="actions">⊙ ⋮</td></tr>`).join('')}
function assetList(){return `<aside class="equipment-list"><h3>Select Equipment</h3><label class="mini-search">⌕ <input placeholder="Search equipment..."></label>${equipment.map((e,i)=>`<div class="asset ${i===0?'selected':''}"><span class="asset-icon">⚙</span><span><b>${e[0]}</b><small>${e[1]}</small></span><em>${128-i*15}</em></div>`).join('')}</aside>`}
function details(page){let title=page==='sop'?'SOP Details':page==='work'?'Work Order Details':page==='report'?'Report Details':page==='pm'?'PM Calendar':page==='records'?'Machine Details':'Equipment Details';return `<aside class="panel detail"><h2>${title}<span style="float:right;font-weight:400">×</span></h2><div class="detail-top"><div class="machine">⚙</div>${badge(page==='sop'?'Published':'Operational')}<h3>${page==='sop'?'SOP-HM-001-001':page==='work'?'WO-2505-0146':'HM-001'}</h3><p>${page==='sop'?'Daily Inspection':'Hammer Mill 01'}</p></div><div class="detail-list"><div><b>Category</b><span>Milling</span></div><div><b>Location</b><span>Plant 1 / Line 3</span></div><div><b>Manufacturer</b><span>ABC Industries</span></div><div><b>Model</b><span>HM-450</span></div><div><b>Last PM Date</b><span>28/05/2025</span></div><div><b>Next PM Date</b><span>28/06/2025</span></div><div><b>Operating Hours</b><span>2,345 hrs</span></div></div><button class="detail-button primary">⊙ View Details</button><button class="detail-button">✎ Edit ${title.replace(' Details','')}</button></aside>`}
function standard(page){let p=pages[page],tabs=page==='pm-schedule'?['All PM Tasks','Due Today','Due This Week','Due This Month','Overdue','Completed']:page==='equipment'?['All Equipment','Critical Assets','Out of Service','Under Maintenance']:page==='sop'?['All SOPs','By Equipment','By Category','Under Review','Outdated']:page==='machine-records'?['All Records','Maintenance','Inspection','Repairs / Overhauls','Parts Replacement','Others']:page==='daily-reports'?['All Reports','My Reports','Pending Approval','Approved','Rejected']:['All Work Orders','My Work Orders','Overdue','Completed','On Hold'];let left=`<section class="panel">${page==='sop'||page==='machine-records'?`<div class="split">${assetList()}<div class="asset-view">${tabsHtml(tabs)}${table(p)}</div></div>`:`${tabsHtml(tabs)}${table(p)}`}</section>`;return left+details(p.type)}
function tabsHtml(tabs){return `<div class="tabs">${tabs.map((t,i)=>`<button class="tab ${i?'':'active'}">${t}</button>`).join('')}</div>`}
function table(p){return `<div class="table-wrap"><table class="data-table"><thead><tr>${p.columns.map(x=>`<th>${x}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${tableRows(p.type)}</tbody></table></div><footer class="pagination"><span>Showing 1 to 10 of ${p.type==='equipment'?186:146} entries</span><span class="pages"><button>‹</button><button class="current">1</button><button>2</button><button>3</button><button>4</button><button>5</button><button>…</button><button>›</button></span><span>Rows per page:　10⌄</span></footer>`}
function kpi(){return `<section class="panel chart-panel"><h2>Work Orders by Type</h2><div class="donut"></div></section><section class="panel chart-panel"><h2>Downtime Trend (Hours)</h2><div class="bars">${[40,65,48,80,56,92,70,120,98,144,110,60].map((h,i)=>`<i style="height:${h}px" data-day="${i+1} May"></i>`).join('')}</div></section><section class="panel chart-panel"><h2>Downtime by Equipment</h2><div class="h-bars">${equipment.slice(0,5).map((e,i)=>`<div><span>${e[1]}</span><i style="width:${200-i*28}px"></i><b>${(6.2-i*.8).toFixed(1)} h</b></div>`).join('')}</div></section><section class="panel chart-panel"><h2>Top 5 Equipment by Downtime</h2>${equipment.slice(0,5).map((e,i)=>`<div class="summary-row"><span>${i+1}　${e[0]}　${e[1]}</span><b>${(6.2-i*.8).toFixed(1)} h</b></div>`).join('')}</section><section class="panel chart-panel"><h2>PM Compliance by Line</h2>${[95,90,82,78,88].map((x,i)=>`<div class="summary-row"><span>Line ${i+1}</span><span style="width:55%;height:8px;background:#dff5e9;border-radius:8px"><i style="display:block;width:${x}%;height:100%;background:#10a565;border-radius:8px"></i></span><b>${x}%</b></div>`).join('')}</section><section class="panel chart-panel"><h2>Work Order Summary</h2>${[['▣','Total Work Orders','146'],['✓','Completed','128'],['◷','In Progress','18'],['⊙','On Hold','6'],['◉','Overdue','12']].map(x=>`<div class="summary-row"><span>${x[0]}　${x[1]}</span><b>${x[2]}</b></div>`).join('')}</section>`}
function render(page){let p=pages[page]||pages.dashboard;document.getElementById('page-title').textContent=p.title;document.getElementById('page-subtitle').textContent=p.sub;document.getElementById('primary-action').textContent=p.action;document.getElementById('metric-grid').innerHTML=metrics(p.metrics);let w=document.getElementById('workspace');w.className='workspace '+(p.type==='kpi'?'kpi-layout':'');w.innerHTML=p.type==='kpi'?kpi():standard(page);document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));location.hash=page}
const standardRender=render;
let accountCache=[];
pages.users={title:'User Accounts',sub:'Create accounts and manage access permissions',action:'+ Add User',metrics:[['Total Users','—','♙','blue'],['Active Accounts','—','✓','green'],['Technicians','—','⚒','orange'],['Engineers','—','◈','purple'],['Developers','—','⚙','red'],['Inactive','—','×','blue']],type:'users'};
function accountRoleLabel(role){return role.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
function userWorkspace(){return `<section class="panel"><div class="tabs"><button class="tab active">All Users</button><button class="tab">Active</button><button class="tab">Technicians</button><button class="tab">Engineers</button><button class="tab">Inactive</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Username</th><th>Full Name</th><th>Role</th><th>Technician ID</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody id="users-table"><tr><td colspan="7" class="loading">Loading accounts…</td></tr></tbody></table></div></section><aside class="panel user-editor"><h2 id="user-form-title">Create User Account</h2><form id="user-form"><input type="hidden" name="id"><label>Username<input name="username" required autocomplete="username"></label><label>Full Name<input name="full_name" required></label><label>Role<select name="role" required><option value="TECHNICIAN">Technician</option><option value="MAINTENANCE_ENGINEER">Maintenance Engineer</option><option value="ADMINISTRATOR_VIEWER">Administrator / Viewer</option><option value="SYSTEM_DEVELOPER">System Developer</option></select></label><label>Technician ID <small>(for technician accounts)</small><input name="technician_id"></label><label>Password <small id="password-help">Required for a new account</small><input name="password" type="password" minlength="8" autocomplete="new-password"></label><label class="check"><input name="is_active" type="checkbox" checked> Active account</label><div class="form-actions"><button type="button" class="detail-button" id="cancel-user">Clear</button><button class="detail-button primary" type="submit">Save Account</button></div><p id="user-form-error" class="form-error"></p></form></aside>`}
function setUserForm(user){let form=document.getElementById('user-form');form.id.value=user?.id||'';form.username.value=user?.username||'';form.username.disabled=Boolean(user);form.full_name.value=user?.full_name||'';form.role.value=user?.role||'TECHNICIAN';form.technician_id.value=user?.technician_id||'';form.password.value='';form.is_active.checked=user?.is_active??true;document.getElementById('user-form-title').textContent=user?'Edit User Account':'Create User Account';document.getElementById('password-help').textContent=user?'Leave empty to keep the current password':'Required for a new account';document.getElementById('user-form-error').textContent=''}
function accountToast(message){let toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
async function loadAccounts(){let target=document.getElementById('users-table');if(!target)return;try{accountCache=await apiRequest('/users');target.innerHTML=accountCache.map(user=>`<tr><td class="code">${user.username}</td><td>${user.full_name}</td><td>${badge(accountRoleLabel(user.role))}</td><td>${user.technician_id||'—'}</td><td>${badge(user.is_active?'Active':'Inactive')}</td><td>${user.last_login?new Date(user.last_login).toLocaleString():'Never'}</td><td><button class="table-button" data-account-id="${user.id}">Edit</button></td></tr>`).join('');let active=accountCache.filter(user=>user.is_active).length;let count=role=>accountCache.filter(user=>user.role===role).length;document.getElementById('metric-grid').innerHTML=metrics([['Total Users',accountCache.length,'♙','blue'],['Active Accounts',active,'✓','green'],['Technicians',count('TECHNICIAN'),'⚒','orange'],['Engineers',count('MAINTENANCE_ENGINEER'),'◈','purple'],['Developers',count('SYSTEM_DEVELOPER'),'⚙','red'],['Inactive',accountCache.length-active,'×','blue']]);target.querySelectorAll('[data-account-id]').forEach(button=>button.addEventListener('click',()=>setUserForm(accountCache.find(user=>user.id===Number(button.dataset.accountId)))))}catch(error){target.innerHTML=`<tr><td colspan="7" class="loading error">${error.message}</td></tr>`}}
function bindAccountForm(){setUserForm();document.getElementById('cancel-user').addEventListener('click',()=>setUserForm());document.getElementById('user-form').addEventListener('submit',async event=>{event.preventDefault();let form=event.currentTarget,values=new FormData(form),id=values.get('id'),error=document.getElementById('user-form-error'),password=values.get('password'),payload={full_name:values.get('full_name').trim(),role:values.get('role'),technician_id:values.get('technician_id').trim()||null,is_active:values.get('is_active')==='on'};if(password)payload.password=password;if(!id){payload.username=values.get('username').trim();if(!password){error.textContent='Password is required for a new account.';return}}try{await apiRequest(id?`/users/${id}`:'/users',{method:id?'PUT':'POST',body:JSON.stringify(payload)});setUserForm();await loadAccounts();accountToast('Account saved successfully.')}catch(exception){error.textContent=exception.message}})}
function renderUsers(){let page=pages.users;document.getElementById('page-title').textContent=page.title;document.getElementById('page-subtitle').textContent=page.sub;document.getElementById('primary-action').textContent=page.action;document.getElementById('metric-grid').innerHTML=metrics(page.metrics);let workspace=document.getElementById('workspace');workspace.className='workspace';workspace.innerHTML=userWorkspace();document.querySelectorAll('.nav-link').forEach(link=>link.classList.toggle('active',link.dataset.page==='users'));location.hash='users';bindAccountForm();loadAccounts()}
render=page=>page==='users'?renderUsers():standardRender(page);
async function initializeAccounts(){if(!getSavedUser()){location.replace('login.html');return}try{let user=await getCurrentUser();localStorage.setItem('user',JSON.stringify(user));document.querySelector('.profile b').textContent=user.full_name||user.username;document.querySelector('.profile small').innerHTML=`<mark></mark> ${accountRoleLabel(user.role)}`;document.querySelectorAll('.developer-only').forEach(link=>link.hidden=user.role!=='SYSTEM_DEVELOPER');if(location.hash==='#users'&&user.role!=='SYSTEM_DEVELOPER')render('dashboard')}catch(error){logout();location.replace('login.html')}}
initializeAccounts();
const logoutButton=document.getElementById('logout-button');
document.querySelector('.profile')?.append(logoutButton);
logoutButton?.addEventListener('click',()=>{logout();location.replace('login.html')});
document.querySelector('.nav-link[data-page="daily-reports"]')?.addEventListener('click',event=>{event.stopImmediatePropagation();location.href='daily-reports.html'},true);
document.getElementById('primary-action').addEventListener('click',event=>{if(location.hash==='#daily-reports'){event.stopImmediatePropagation();location.href='daily-report-form.html'}},true);
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));document.getElementById('primary-action').addEventListener('click',()=>{let t=document.getElementById('toast');t.textContent='Demo interface: this action will connect to the backend next.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)});document.getElementById('global-search').addEventListener('input',e=>{document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase()))});render(location.hash.slice(1)||'dashboard');
